### ISSUE TITLE
JSON-LD: application/ld+json vs .well-known

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/.well-known#10]
Its worth noting that JSON-LD has some opinions about well-known URIs... apparently they don't like them, and prefer to use HTTP headers...

https://web-payments.org/specs/source/secure-messaging/#the-key-registration-process

https://json-ld.org/spec/latest/json-ld-api-best-practices/#use-json-ld

Personally, I'm a bigger fan of well-known URIs than varying responses based on headers, especially since you typically need to configure a web server to support custom headers.

**Comment by peacekeeper** [comment]
I don't think it's right to say that JSON-LD doesn't like .well-known URIs. I think it depends on the situation. I wouldn't interpret those links as saying that we can't use .well-known for discovering a DID from an HTTP URL.

**Comment by OR13** [comment]
@peacekeeper thanks for your comments on this.

We decided to specifically not make the `did-configuration.json` jsonld (we use an array of objects and we rely on the order of the array).

I think this issue is less relevant now that the file is explicitly not jsonld.

I'm gonna close, for now.
