### ISSUE TITLE
Be specific about Base64 encoding - needs to be Base64 URL encoding

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/.well-known#11]

**Comment by OR13** [comment]
I think this is implied by the use of JWT/JWS. but its probably a good idea to double check.

**Comment by ptinson-mattr** [comment]
It is implied, perhaps just remove the base64 comment and state it must be a valid JWT as defined in https://tools.ietf.org/html/rfc7519? Thoughts.
