### ISSUE TITLE
Reduce to ReSpec Only

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/.well-known#14]
We have a lot of duplicate markdown / respec like stuff.

We need to move everything that is "spec like" from:

https://github.com/decentralized-identity/.well-known/blob/master/resources/did-configuration/demo/README.md

into:

https://github.com/decentralized-identity/.well-known/blob/master/resources/did-configuration/index.html

The demo README should just point to the spec and describe development setup and tips.

**Comment by OR13** [comment]
I'd rather not make the call of what to delete, since @csuwildcat wrote most of this. I'm assigning you.

**Comment by csuwildcat** [comment]
I think we should just blow away all the spec/definitional content from the readme and leave the readme to be about the setup/developer instructions you added to it. This way the spec is all the spec stuff, and this turns into the dev side of how to install/run the required bits.

**Comment by OR13** [comment]
I'm fine with doing that, I just want to make sure that if there is any copy that is in markdown that is valuable, we don't just loose it.

**Comment by csuwildcat** [comment]
I think this is done, right?

**Comment by OR13** [comment]
yes I think so. There is some leftover readme content in the demo folder: https://github.com/decentralized-identity/.well-known/tree/master/resources/did-configuration/demo

but I think thats ok, closing for now.
