### ISSUE TITLE
Support for virtual hostnames

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/.well-known#15]
Could you add support for multiple hostnames, or if the intention was to support that, to make that explicit.

**Comment by csuwildcat** [comment]
Can you expound upon what that would look like? The connection between each assertion and the domain was expected to be 1:1, with all assertions linking to only the domain under which the resource is located.

**Comment by OR13** [comment]
I think this feature request is to update the domain to an array:

```
"domains": ["app1.example.com", "example.com"]
```

Then:

https://example.com/.well-known/did-configuration.json
https://app1.example.com/.well-known/did-configuration.json

I would expect the token to be present in both `entries` if the token contained such as claim.

The benefit of this approach would be that a DID controller could make a single jwt which covered all the domains it wanted to be authoritative for, and then wait for web admins to add it to the configuration.

The downside would be that it would encourage excessive context sharing, why does anyone resolving: https://example.com/.well-known/did-configuration.json care about app1?

Also the assertion might be filled with domains which are not correctly linked, and processing of the assertion could become expensive (how many domains can be listed in an assertion), etc...

I'm in favor of not implementing support for multiple domains in the first version of the spec.

**Comment by csuwildcat** [comment]
Oh, I didn't realize what he was saying at first, but yeah, I think we should avoid this for a variety of reasons, including the complexities you note here.

**Comment by csuwildcat** [comment]
Closing, as this behavior is intentionally disallowed.
