### ISSUE TITLE
Unclear when verification stops and when verification was successful

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/.well-known#17]
The entry array supports multiple DIDs. It is unclear when the verification process stops. A few questions that I have:

- Does the verification stop when any of the entries was failed to verify? That might be an issue in case virtual hostnames are supported.

- Does the verification stop when the first entry was successfully verified?

- Can the verifier choose which entry to pick first, i.e., which DID (method) to resolve, or is the order mandated?

**Comment by csuwildcat** [comment]
Each DID assertion is intended to be verified on a per entry basis, so one failing only means that the assertion that failed or was malformed is dropped/errors.

**Comment by OR13** [comment]
We need to explicitly define verification in the spec. the end result of completing a verification of a `did-configuration` is a list of DIDs that passed and a list that failed. its up to the verifier to decide which DIDs they want to work with, they should not use DIDs who failed verification.

**Comment by csuwildcat** [comment]
The resource is a list of independent assertions of linkage of a DID to a domain, thus there is no assumption that all entries must validate for the resource to be deemed valid. I have added language to clarify this and specify what to do in the case a single item is processed and found to be invalid.

To elaborate on the practical, the resource itself may be prefetched and held by the requester until such time that a DID-based interaction occurs. In this case, the requesting party would only validate the whole document for basic structure, in accordance with this section: https://identity.foundation/.well-known/resources/did-configuration/#resource_validation. At a later time, when a DID-based interaction is triggered, the requesting party holding the resource may attempt to validate one, all, or some of the DID linkage assertions, at their election. Each entry they process would be processed in accordance with the steps outlined here: https://identity.foundation/.well-known/resources/did-configuration/#validation-of-domain-linkage-assertions.

**Comment by awoie** [comment]
That sounds good! From my perspective, the issue can be closed.

**Comment by awoie** [comment]
I looked at the current version and the spec is fine by me.
