### ISSUE TITLE
Bi-directional statement in abstract

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/.well-known#18]
In the abstract of the current spec, the following statement is made 

```
The DID Configuration resource provides proof of a bi-directional relationship between the controller of an Internet domain and a DID via cryptographically verifiable signatures that are linked to a DID's key material
```

Can we clarify further what is meant by this? This implies you can start with a did and discover associated domains from it? That may just be my interpretation but to be clear, the current design does not allow this?

**Comment by tplooker** [comment]
Re-reading this I understand the intent further now. The resource provides the linkage, between these two identifiers. However how the resource is discovered/deferenced relies on the prior knowledge of the domain, you cannot start with just the did and discover this resource unless it was embedded in a did document?

**Comment by csuwildcat** [comment]
The bi-directional relationship is the association created by the signing of the DID owner over the domain string, and the domain owner placing it at the designated origin. It never says anything about discovery, so I'm not sure how that's being read into the non-normative Abstract language.

**Comment by peacekeeper** [comment]
Our [DNS-DID spec](https://datatracker.ietf.org/doc/draft-mayrhofer-did-dns/) mentions the possibility of a "backreference to the DNS domain name". I agree that this is not really needed and that the bi-directional relationship can be proven with a signature, as explained by @csuwildcat.

I haven't heard of any use case where actual discovery of a domain name from a DID is needed, do you have one in mind @tplooker ? Note that the DID spec mentions a potential property called "equivID" for discovering [equivalent identifiers](https://w3c-ccg.github.io/did-spec/#equivalence) from a DID.

**Comment by OR13** [comment]
Yes, we should add clarifying language regarding discovery. 

You can discover associated DIDs from the domain, but not domains from a particular DID.
