### ISSUE TITLE
Add 307 redirect convention to allow subdomains to defer to base domain

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/.well-known#19]

**Comment by csuwildcat** [comment]
@OR13 any input, or is that last change good to address the use case the folks at IIW presented?

**Comment by OR13** [comment]
I'm not sure about this. It feels like this will widen attack surface. I think I prefer a separate well known uri for subdomains.

**Comment by csuwildcat** [comment]
Redirection language has been removed, as this is not in scope for the initial 0.1.0 publication goal. There were some security issues called out that would need to be revisited, if we desired to pursue this in a future revision of the spec. Removed language can be viewed here: https://github.com/decentralized-identity/.well-known/compare/97d95aa24522...8c59db817382
