### ISSUE TITLE
Unclear why the domain is part of the JWT, and why it is called JWT and not proof?

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/.well-known#23]
I just read the spec: https://identity.foundation/specs/did-configuration/

And it was unclear to me what the value of domain is in the claim. Or where the JWT is issued from?

Will it be the users of that did entry who signs of a JWT or something else?
The domain is there to match the domain the well-known is under?
Because this well-known document will be built up by the domain owner so he will only put in trustable information.

**Comment by OR13** [comment]
yes, the domain controller and the DID controller both have to coordinate to put a JWT int he correct spot.

**Comment by csuwildcat** [comment]
If the domain wasn't in the claim, there wouldn't be any proof that the controller of the DID in question intended to link their control of their DID to their control of the domain under which the well-known resource resides.

**Comment by csuwildcat** [comment]
The property was named `jwt` to be specific to the type of proof value, just in case the assertion object definition is ever expanded to include other types of proof values. Being specific also allows the consuming developer to invoke the proper code to evaluate the type of proof described, vs having to sniff the object to detect what type it might be before evaluating.

**Comment by vongohren** [comment]
Thanks for that clarifying information, it does makes sense :)

**Comment by tplooker** [comment]
@vongohren are you happy to close this issue?

**Comment by vongohren** [comment]
@tplooker yes, il close now :)
