### ISSUE TITLE
DID to domain discovery - Using service endpoints

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/.well-known#26]
This issue is related to a previous discussion in #18.

Say the following credential has been issued

```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ], 
  "id": "1872", 
  "type": ["VerifiableCredential", "AlumniCredential"], 
  "issuer": "did:example:c276e12ec21ebfeb1f712ebc6f1", 
  "issuanceDate": "2010-01-01T19:73:24Z", 
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "alumniOf": {
      "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
      "name": [{
        "value": "Example University",
        "lang": "en"
      }, {
        "value": "Exemple d'Université",
        "lang": "fr"
      }]
    }
  },
  "proof": {
    "type": "RsaSignature2018",
    "created": "2017-06-18T21:19:10Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:example:c276e12ec21ebfeb1f712ebc6f1#key-1",
    "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X
      sITJX1CxPCT8yAV-TVkIEq_PbChOMqsLfRoPsnsgw5WEuts01mq-pQy7UJiN5mgRxD-WUc
      X16dUEMGlv50aqzpqh4Qktb3rk-BuQy72IFLOqV0G_zS245-kronKb78cPN25DGlcTwLtj
      PAYuNzVBAh4vGHSrQyHUdBBPM"
  }
}
```

For human readability purposes, credential processing software in some instances would benefit from being able to substitute the domain name if there is one associated to the issuers DID in a UI rendering for this credential. However, the current spec does not support DID to domain discovery.

To support this functionality we could use DID service endpoints in the following way.

Assume the domain of `example.edu` hosts a `/.well-known/did-configuration` resource establishing a link with `did:example:c276e12ec21ebfeb1f712ebc6f1`

If the DID document of `did:example:c276e12ec21ebfeb1f712ebc6f1` looked like the following, the well-known resource could be discovered from the DID.

```
{
  "@context": "https://www.w3.org/ns/did/v1",
  "id": "did:example:c276e12ec21ebfeb1f712ebc6f1",
  "authentication": [{
    "id": "did:example:c276e12ec21ebfeb1f712ebc6f1#key-1",
    "type": "RsaVerificationKey2018",
    "controller": "did:example:c276e12ec21ebfeb1f712ebc6f1",
    "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----\r\n"
  }],
  "service": [{
    "id":"did:example:c276e12ec21ebfeb1f712ebc6f1#domain-link",
    "type": "DomainLink",
    "serviceEndpoint": "https://example.edu/.well-known/did-configuration"
  }]
}
```

Thoughts @csuwildcat @peacekeeper @OR13?

I'm unconvinced whether this would need to be directly in this specification it could just be an optional discovery mechanism?

**Comment by OR13** [comment]
We've had some discussion about this concept before, just today I was talking the Factom folks about this other direction. cc @Cahl-Dee 

I think it would be very helpful to be able to put a domain name with a checkmark next to an VC issued by a linked did.

I'd be in favor of defining this behavior in the spec.

**Comment by csuwildcat** [comment]
I really hope we can avoid encouraging atomic domain linkage entries like this in DID Documents, because the size bloat could get pretty significant. Personally, I feel a better route would be to codify a single Service Endpoint that could host any size list of domains the controlling entity wanted, signed with their DID keys, which could be fetched via a deterministic, inferentially knowable API, allowing the requester to check any of the DID Configurations of the domains in the list - you know like a hub where signed and/or encrypted data like this can be stored so we don't needlessly overload the scarce resources of the DID network substrate ;)

**Comment by csuwildcat** [comment]
@tplooker with Identity Hubs, all you would need to do is create a schema that defined how to represent a list of domains that have DID Configuration docs at their well-known endpoints, and you could inferentially know how to look them up via the schema/object based lookup Collections provide.

**Comment by csuwildcat** [comment]
I'll take a little poetic liberty with a riff on a famous George Washington quote:

"It follows then as certain that night succeeds the day, that without a decisive Identity Hub (personal datastore) with a semantically based, inferentially knowable API, we can do nothing definitive, and with it, everything honorable and glorious."

**Comment by OR13** [comment]
So something like:

```
...
"service": [{
    "id":"did:example:c276e12ec21ebfeb1f712ebc6f1#domain-links",
    "type": "DomainLinks",
    "serviceEndpoint": "https://hub.example.edu/collections/did-configurations"
  }]
...
```

which in turn provides an a bunch of points to endpoints like:

```
https://example.edu/.well-known/did-configuration
```

As a DID Controller, use my hub to find all the domains I am authoritative for... then use well known configuration to confirm that the domain controller still wants me to be.

Another alternative is to embed the domain in the VC proof, that way you can always lookup its configuration... for example:

```
"proof": {
    "type": "RsaSignature2018",
    "created": "2017-06-18T21:19:10Z",
    "proofPurpose": "assertionMethod",
    "domain": "edu.example.com",
    "verificationMethod": "did:example:c276e12ec21ebfeb1f712ebc6f1#key-1",
    "jws": "eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TCYt5X
      sITJX1CxPCT8yAV-TVkIEq_PbChOMqsLfRoPsnsgw5WEuts01mq-pQy7UJiN5mgRxD-WUc
      X16dUEMGlv50aqzpqh4Qktb3rk-BuQy72IFLOqV0G_zS245-kronKb78cPN25DGlcTwLtj
      PAYuNzVBAh4vGHSrQyHUdBBPM"
  }
```

**Comment by tplooker** [comment]
@OR13 I was under the impression that the domain field in the a linked data proof was in-fact equivalent to the audience field in a JWT, i.e it sets the domain the proof is valid for? See [here](https://w3c-dvcg.github.io/ld-proofs/#terminology), the example in the definition of `mycorp-level3-access` lead me to believe that? Rather than the field meaning the domain of the issuer?

**Comment by tplooker** [comment]
@csuwildcat I'm happy to add the indirection you suggest as an option, however if you are a simple issuer who owns a single domain, I think the service endpoint should take you straight to the domain you are wanting to express a link to?

**Comment by OR13** [comment]
@tplooker you are correct. 

```
A string value that specifies the operational domain of a digital proof. This could be an Internet domain name like example.com, an ad-hoc value such as mycorp-level3-access, or a very specific transaction value like 8zF6T$mqP. A signer could include a domain in its digital proof to restrict its use to particular target, identified by the specified domain.
```

So pretty much the issuer can use this for whatever they want it seems.... when you resolve the well known did configuration and find their key or don't find their key, you can decide what to do. If you do find their key, you known that the did is controlled by the same entity.

**Comment by OR13** [comment]
In any case, this issue is about how you can go from a DID or a VC issued by a DID to a Domain.

There are clearly a couple ways.

1. You can services
2. You can use a hub
3. You can include a domain in a VC, and check that domain's configuration against the DID that issued it.

I think perhaps we should separate the concept of how to use well known did configuration with VCs, from the easier problem of how to link from a DID to a Domain.

There are some DID Methods that don't support service endpoints, for those, you only chance would be to include a domain value in the proof (did key for example).

**Comment by OR13** [comment]
You could extend your DID Document with a value `linkedDomains`... I think everyone would probably would rather use services though.

**Comment by csuwildcat** [comment]
> So something like:
> 
> ```
> ...
> "service": [{
>     "id":"did:example:c276e12ec21ebfeb1f712ebc6f1#domain-links",
>     "type": "DomainLinks",
>     "serviceEndpoint": "https://hub.example.edu/collections/did-configurations"
>   }]
> ...
> ```

If you just had a Hub Service Endpoint, you would not need this specific sub-reference, consumers could just form a request to fetch this type of object, given the route can be deterministically inferred.

**Comment by OR13** [comment]
I can't wait till we have a place to develop  edv / hubs stuff...

**Comment by OR13** [comment]
Thinking a bit more about this.

I'm holding a did:example:123... I resolve it and ask it's hub for all websites that it is authoritative for, I get back a list, and use the well known did configuration to check for the domain linkage assertion. lets assume that 50% of them are still valid, and 50% fail (webmaster removed the assertion or did controller lied).

What is the next step?

I could report vulnerabilities by encrypting messages for the did and sending them to the webmaster.

I could send some crypto to an address linked to the did as a donation to the website.

I could crawl the whois information for the websites and start building a graph of related content to the did.

It seems desirable that given a credential issued by did:example:123 I should know which website the credential is associated with. 

If the same did is configured for multiple domains, I could use a seperate key per domain, or a could include a domain property in the VC.

This would help resolve a VC issued by did:example:123 to a domain like example.com, and a user could trust that the VC was from example.com.

I think of all these options its best for the issue to include the domain in the credential, such that the verifier knows which domain should be checked with well known did configuration.

**Comment by OR13** [comment]
@csuwildcat this is the open issue that is related to your desire to embed related links in service endpoints.

**Comment by OR13** [comment]
There was recently a desire to link to domains from a did document... and then use the well known uri for confirming the link.


Here is an example of what a service defintion might look like:


Based on https://w3c.github.io/did-core/#example-2-minimal-self-managed-did-document

```
{
  "@context": "https://www.w3.org/ns/did/v1",
  "id": "did:example:123456789abcdefghi",
  "authentication": [{
    
    "id": "did:example:123456789abcdefghi#keys-1",
    "type": "RsaVerificationKey2018",
    "controller": "did:example:123456789abcdefghi",
    "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----\r\n"
  }],
  "service": [{
    "id":"did:example:123456789abcdefghi#vcs",
    "type": "LinkedDomains",
    "domain": ["example.com", "identity.foundation"]
  }]
}
```

**Comment by peacekeeper** [comment]
I know this has already been mentioned elsewhere, just also wanted to note here that `domain` is already defined in the Security Vocabulary JSON-LD context with different meaning: https://w3c-ccg.github.io/security-vocab/#domain

**Comment by OR13** [comment]
https://w3c-ccg.github.io/security-vocab/#domain

I suggest we not use the term `domain`... and instead define `domains` in did core, for the purposes of supporting linkage like this.

**Comment by dlongley** [comment]
The definition for "domain" in the security vocabulary is perhaps a bit too functional at the moment, instead of declarative -- if people are coming to the conclusion that another term is needed (I disagree). Yes, "domain" *is* used to express a domain associated with a proof, but that fact does not mean that you can't use "domain" to associate one or more domains with a service as well.

**Comment by OR13** [comment]
@dlongley thanks! I have opened: https://github.com/w3c-ccg/security-vocab/issues/37

Very helpful to be able to use this term without creating a new one.

**Comment by csuwildcat** [comment]
The DID Service Endpoint was defined in this PR: https://github.com/decentralized-identity/.well-known/commit/bb401f4dcaabab15b524a71fc612fb7f87ec5a8e
