### ISSUE TITLE
Add did:web example

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/.well-known#3]
I think that this repo can be used to test `did:web`, it would be awesome to get an example commited.

@pelle @awoie Can one of you link me to a did:web example, I will add it here, and back link to whatever you wish.

**Comment by OR13** [comment]
Per comments from @awoie Added example: https://github.com/decentralized-identity/.well-known/commit/3e08219cc7bff24082675188fabcb20d9fb9cec3

**Comment by awoie** [comment]
@OR13 did:web uses the old `owner` syntax. that needs to be fixed. the other two public keys don't have an `owner` attribute. you might need to fix that.

**Comment by awoie** [comment]
looks good now!
