### ISSUE TITLE
Which key is used to sign an assertion?

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/.well-known#39]
> signed with the specified DID's keys

here and elsewhere there is an implication but multiple key**s** are signing the assertions in the configuration file entries. But a single assertion can only be signed by a single key. Is the expectation of that multiple assertions should be made, one per signing key? (To prove possession of all signing keys?) Or is the idea that the did owner can pick any signing key and make an assertion with just that one? I assume it is the latter, in which case we should update the language to use singular nouns and perhaps provide guidance how to identify signing keys within the did document.

**Comment by OR13** [comment]
@jmandel great question... if the assertion is a VC... keys listed in the `assertionMethod` verification relationship should be used.

- https://www.w3.org/TR/vc-data-model/#proofs-signatures-0
- https://www.w3.org/TR/did-core/#assertionmethod
- https://www.w3.org/TR/did-spec-registries/#assertionmethod

Since the well known did configuration credentials are VCs... keys in the `assertionMethod` section of a DID Document MUST be used.

**Comment by OR13** [comment]
See also: https://identity.foundation/.well-known/resources/did-configuration/#did-configuration-resource-verification

Section 5:

> Using the retrieved DID document, the implementer MUST validate the signature of the Domain Linkage Credential against key material referenced in the assertionMethod section of the DID document.

**Comment by OR13** [comment]
The current spec does not support "Proof Sets or Proof Chains" (which are not supported by JWTs at all)... so each VC has only one associated `verificationMethod`.

**Comment by jmandel** [comment]
Thanks -- so to be clear, is it "enough" (per the current spec, or its intent) to pick *any one* `assertionMethod` key and sign an assertion with that one? That will bind "the whole DID"? Or should relying parties care about *which* key was used?

**Comment by OR13** [comment]
@jmandel RPs should not have any opinion about which key is used, similar to how they have no opinion about which JWK in the well known JWKs URI in OIDC is used :) 

If the key used to issue the VC is not present in `assertionMethod` the VC is considered invalid / revoked.... so the issuer might consider how key rotation will impact credential lifetime... this is also similar to the decisions authorization servers need to make.

**Comment by OR13** [comment]
Keys listed in the `assertionMethod` verification relationship should be used to issue verifiable credentials, keys in the `authentication` relationship should be used for verifiable presentations. Both of these are defined in the vc data model spec, not this one. closing.
