### ISSUE TITLE
The JWT in example 2 uses "domain" in place of "origin"

### ISSUE THREAD

**Issue by p2-apple** [decentralized-identity/.well-known#41]
The [example 2](https://identity.foundation/.well-known/resources/did-configuration/#example-2) contains one JSON-LD and one JWT example domain linkage credential. The JWT form uses `credentialSubject.domain` instead of `credentialSubject.origin` and may need to be updated.

**Comment by OR13** [comment]
@csuwildcat This is on you :)

**Comment by csuwildcat** [comment]
Will be submitting a PR for this soon.

**Comment by OR13** [comment]
Closing, there are currently no JWT examples / they were way out of date.
