### ISSUE TITLE
Relax body size limit (16 kilobytes or more)

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/.well-known#42]
We're trying to publish a did-configuration.json file that uses a long-form DID -- see https://c19.cards/.well-known/did-configuration.json. The body is already larger than 8KB even with only a single `entry` in the array.

Is there a compelling reason to impose such a stringent limitation? (If so, we can probably drop parameters from the long-form DID in this case, but I'm anticipating that other use cases will require binding to multiple DIDs, which makes the limit even tougher.)

**Comment by csuwildcat** [comment]
I will be removing the limit in a PR, as the file will expand to include other config values anyway,

**Comment by jmandel** [comment]
Thanks. Can you comment on the original motivation for imposing a (tight) limit, BTW?

**Comment by OR13** [comment]
I believe the limit is now the max json object size. @jmandel can you comment and close if this is addressed?

**Comment by jmandel** [comment]
Thanks -- "a tolerance set by the implementer" (current language) avoids the hard limit.
