### ISSUE TITLE
Demo / Reference Implementation is nonfunctional 

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/.well-known#45]
Per the documentation here: https://github.com/decentralized-identity/.well-known/tree/master/resources/did-configuration

@csuwildcat indicated in DIF slack that he could not run the example / demo:

```
$ npm start
> did-configuration@0.1.0 start C:\repos\well-known\resources\did-configuration
> react-scripts start
'react-scripts' is not recognized as an internal or external command,
```

Possibly a windows issue.

**Comment by OR13** [comment]
I will attempt to resolve this issue when I get some spare cycles.

**Comment by ipatka** [comment]
@csuwildcat I was unable to reproduce. From the `did-configuration` folder I did:

`npm ci`
`npm run start`

using node v12, on a Mac

Maybe `react-scripts` needs to be specified as a dev dependency explicitly? Or we could change package.json `start` script to 
`node_modules/.bin/react-scripts start`

<img width="987" alt="Screen Shot 2020-09-01 at 3 05 17 PM" src="https://user-images.githubusercontent.com/4401444/91895032-90e47f00-ec64-11ea-8ba5-1365fd080582.png">

**Comment by csuwildcat** [comment]
> using node v12, on a Mac
> 
> Maybe `react-scripts` needs to be specified as a dev dependency explicitly? Or we could change package.json `start` script to
> `node_modules/.bin/react-scripts start`

Yeah, I am thinking it's either some sort of dependency difference or an issue with references between OSes (I was using Windows, but can test with WSL Ubuntu as well)

**Comment by OR13** [comment]
I would guess this may be pathing related... I have been bitten by windows pathing issues my whole life as a developer.

@ipatka if you got this working, would you mind opening a PR to ensure that the demo is using data that conforms to the latest spec?

**Comment by OR13** [comment]
demo was removed
