### ISSUE TITLE
Definition of Origin

### ISSUE THREAD

**Issue by Sakurann** [decentralized-identity/.well-known#48]
Suggesting pointing definition of Origin to IETF's The Web Origin standard [https://tools.ietf.org/html/rfc6454#section-3.5](https://tools.ietf.org/html/rfc6454).
This would not only make this well-known specification more stable, but also clarify that the specification applies to subdomains, which could be made more explicit in the spec.

**Comment by OR13** [comment]
@csuwildcat @tplooker didn't we do this?

**Comment by OR13** [comment]
I think this was done here: https://identity.foundation/.well-known/resources/did-configuration/#origins 

closing
