### ISSUE TITLE
Should well known did configuration support issuer styling 

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/.well-known#51]
see https://github.com/decentralized-identity/credential-manifest/issues/19#issuecomment-722566890

**Comment by TomCJones** [comment]
This is part of the problem I have with DID taking some of the generic UX issues into this spec. If this is a UX issue it belongs at a higher level than DID spec.

**Comment by OR13** [comment]
this is the repo for https://identity.foundation/.well-known/resources/did-configuration/

which is a higher level spec then did core.

**Comment by OR13** [comment]
IMO, no this spec should only include links to other specs like the CM / PE... we should not embed their objects here.
