### ISSUE TITLE
JWT inconsistencies: .json file extension and spec wording

### ISSUE THREAD

**Issue by letmaik** [decentralized-identity/.well-known#67]
This spec supports JSON-LD as well as JWT as format for the domain linkage credential resource. However, there are a few inconsistencies:
- The filename is always `.json`, which seems wrong for JWT, since the media type would be `application/jwt` and not `application/json` and most web servers would by default send the incorrect media type in the case of JWTs.
- Section 3 of the spec starts with "Given an origin, https://example.com, fetch the DID Configuration resource" and "Provided the call returns a successful response, ... parse the body as JSON" and "The DID Configuration resource MUST be a valid JSON object". This wouldn't work for JWT.

**Comment by OR13** [comment]
the file is a JSON file, that contains VCs which may be encoded as compact JWT or JSON-LD.

**Comment by OR13** [comment]
for example: https://identity.foundation/.well-known/did-configuration.json

**Comment by letmaik** [comment]
Oh, you're absolutely right, my bad :)
